keys:
  - &the-entertaining-nios-vm age1hsaqjyj4mtmdyyqtetjn0twlfeppn0vxla724tl9uy702lv0qp7sxmejq5
  - &the-entertaining-nios-laptop age182ymkfkp0gx8lu66gd4c5dfhq8632p42898h5a4p20xdln75j4fq5ssa6y
creation_rules:
  - path_regex: hosts/the-entertaining-nios-vm/secrets/.*\.yaml$
    key_groups:
      - age:
          - *the-entertaining-nios-vm
  - path_regex: hosts/the-entertaining-nios-laptop/secrets/.*\.yaml$
    key_groups:
      - age:
          - *the-entertaining-nios-laptop
