{ vars, ... }:
{
  imports = [
    ./features.nix
    ./disko.nix
    # hardware-configuration.nix and secrets.nix are added once this host is
    # actually bootstrapped: the former is generated by nixos-anywhere, the
    # latter follows the age-key onboarding steps in the guide's Secrets
    # Management section. Until then this host isn't wired into flake.nix's
    # nixosConfigurations either — see the-entertaining-nios-vm for the
    # pattern once both exist.
    ../../profiles/base.nix
    ../../modules/services/snapper.nix
  ];

  networking.hostName = vars.system.hostName;
  time.timeZone = vars.system.timeZone;
  console.keyMap = vars.system.keyMap;

  # Provisional: the latest released stable at scaffold time. Reconfirm
  # against the actually-released version when this host is bootstrapped for
  # real, then leave it untouched — it only marks the compatibility baseline
  # from first install, same rule as the-entertaining-nios-vm.
  system.stateVersion = "26.05";
}
