# User half of Noctalia Shell v5 (theming, wallpaper) — the system half
# (package, Bluetooth/UPower/power-profiles wiring, Cachix substituter)
# lives in modules/desktop/noctalia.nix. Self-gates on osConfig.features.niri
# the same way home/niri.nix does.
{
  lib,
  pkgs,
  osConfig,
  vars,
  noctalia,
  ...
}:
let
  opacity = import ./transparency.nix;

  # THE shared shape/typography vocabulary for the whole desktop. Colors were
  # already unified long before this (Noctalia's template pass drives fifteen
  # targets off the wallpaper palette); shape, font and density were not —
  # niri rounded windows to 20px, Noctalia's bar to its own default 12px,
  # adw-gtk3 to whatever libadwaita ships, and Qt's Fusion style to nothing at
  # all, with no single place saying what "this desktop's corner radius" is.
  #
  # These live here, in the Noctalia module, rather than in a standalone
  # home/style.nix, because Noctalia is the component that can actually *act*
  # on them everywhere: it owns its own surfaces directly, and its template
  # engine can reach the one place Nix otherwise can't — the live-symlinked
  # niri KDL (see docs/live-dotfiles.md). Anything a plain Nix module can set
  # (home/gtk.nix's font) reads the same numbers by hand and is commented to
  # say so; there are few enough consumers that a second source of truth would
  # cost more than it saves.
  style = {
    # Applied to niri's window corners (via the generated template below) and
    # to Noctalia's bar. Noctalia's panels/launcher/control-center don't take
    # a pixel radius — they scale off corner_radius_scale instead, kept at its
    # 1.0 default since Noctalia's own internal radii are already tuned to
    # read as the same family as this value.
    radius = 16;

    # Matches modules/system/fonts.nix's fontconfig sansSerif default. Set
    # explicitly rather than left as Noctalia's "sans-serif" default so the
    # bar doesn't silently drift if that fontconfig default ever changes.
    font = "Adwaita Sans";
  };

  # The niri half of the shape vocabulary, rendered by Noctalia's own template
  # engine into ~/.config/niri/noctalia-style.kdl and included by
  # home/niri/config.kdl.
  #
  # Why a template and not an ordinary xdg.configFile: home/niri/cfg/*.kdl are
  # deliberately out-of-store symlinks into the operator's live ~/.dotfiles
  # clone so keybinds can be edited without a rebuild, and a static KDL file
  # cannot read a Nix value. Generating the *template input* from Nix
  # (pkgs.writeText below) keeps `style` above as the single source of truth
  # while letting the file land somewhere niri can include it — exactly the
  # mechanism already proven by noctalia.kdl, which is how niri's focus-ring
  # and border colors already track the wallpaper.
  #
  # Deliberately only a window-rule. niri *does* merge duplicate top-level nodes
  # across includes (Noctalia's builtin "niri" template already emits a `layout {}`).
  # Layout structure (focus-ring, gaps, etc.) stays in home/niri/cfg/layout.kdl
  # so there's a single file to edit rather than scattering it across includes.
  # See docs/decisions.md for the investigation that established this.
  niriStyleTemplate = pkgs.writeText "niri-style.kdl.tmpl" ''
    // Generated by Noctalia's template engine from home/noctalia.nix's
    // `style` block. Do not edit — rewritten on every re-theme pass.
    window-rule {
        geometry-corner-radius ${toString style.radius}
        clip-to-geometry true
    }
  '';
in
{
  imports = [ noctalia.homeModules.default ];

  config = lib.mkIf osConfig.features.niri {
    programs.noctalia = {
      enable = true;
      # Supervised (restart-on-failure, journalctl logging) rather than a
      # niri spawn-at-startup line — paired with launch_apps_as_systemd_services
      # below, per upstream's own recommendation for this combination.
      systemd.enable = true;

      settings = {
        shell = {
          launch_apps_as_systemd_services = true;

          # Typography and shape, the two axes this config never declared at
          # all before. font_family defaulted to the literal string
          # "sans-serif" and corner_radius_scale to 1.0 — both fine values,
          # but nothing recorded that they were *chosen*, so nothing stopped
          # them disagreeing with niri and GTK. See the `style` let-block.
          font_family = style.font;

          # 0 = square, 1 = default, 2 = extra rounded. Kept at Noctalia's
          # own default: its internal panel radii at 1.0 already read as the
          # same family as style.radius, and the two knobs aren't in the same
          # unit (this is a multiplier, style.radius is pixels), so there is
          # no arithmetic that would "match" them more correctly.
          corner_radius_scale = 1.0;

          # Blur/transparency is OFF for now, at the operator's request. The
          # value below comes from home/transparency.nix, now 1.0 — see that
          # file for why the whole mechanism was neutralized rather than
          # deleted, and home/niri/cfg/rules.kdl for the commented-out
          # compositor half.
          #
          # THE setting that makes Noctalia's own surfaces translucent at
          # all. It defaults to "solid" — every panel (launcher, control
          # center, clipboard, session, wallpaper picker) renders fully
          # opaque, which silently defeated the entire blur setup: niri
          # can only blur *behind* a surface that has something transparent
          # to show it through. Confirmed live by screenshotting the
          # launcher before and after: "solid" gives a flat dark panel,
          # "glass" gives a translucent one with the wallpaper visibly
          # blurred through it. The other values are "soft" (translucent,
          # less pronounced) and "solid".
          #
          # The TOML path is [shell.panel], NOT [panels], despite Noctalia's
          # own settings *schema* filing this option under "panels"
          # (settings.schema.panels.transparency-mode) and its option values
          # under "shell" (settings.options.shell.panel-transparency.glass).
          # Neither of those is the config path. Found by writing candidate
          # sections and reading Noctalia's own startup warnings, which
          # report both "<section>: unknown section" and
          # "<section>.<key>: unknown setting" — [panels], [shell] and a
          # dozen other guesses were all rejected that way. If this ever
          # appears not to apply, check `journalctl --user -u noctalia` for
          # exactly those warnings before assuming the value is wrong: an
          # unknown key is ignored silently apart from that one line.
          # Was "glass". Set back to Noctalia's own default so every panel
          # renders fully opaque — this is the Noctalia half of turning blur
          # off, and it is the half that actually matters: niri can only blur
          # *behind* a surface that has client-side alpha, so an opaque panel
          # makes the compositor-side blur rules inert regardless of what
          # rules.kdl says.
          panel.transparency_mode = "solid";

          # Both were previously undeclared defaults. Stated explicitly now
          # so the panel outline and shadow are a recorded decision rather
          # than something that could change under a Noctalia update without
          # anyone noticing — the same reasoning that put every other default
          # in this file in writing.
          panel.borders = true;
          panel.shadow = true;

          # Also previously undeclared. With transparency off, the shadow is
          # what keeps panels legible as separate surfaces against a busy
          # wallpaper — the job the blur used to do. Values are Noctalia's own
          # defaults, kept because they were already right, not because they
          # were unexamined. Nests under [shell.shadow], NOT a top-level
          # [shadow] — example.toml is explicit about this, and Noctalia
          # reports an unknown *section* only as a single startup warning
          # line, so getting it wrong would look exactly like it working.
          shadow = {
            direction = "down";
            alpha = 0.55;
          };
        };

        # Fires after every full re-theme pass completes (confirmed via
        # reading application_services.cpp/template_apply_service.cpp
        # directly: TemplateApplyService's setAfterApplyCallback, invoked
        # once builtin+community+user templates have all finished for that
        # palette resolution — template-independent, unlike the per-user-
        # template post_hook in theme.templates.user). Needed because GTK
        # apps only re-scan icon-theme *content* changes (e.g. Papirus'
        # folder-color symlinks, recolored by the "papirus-icons" community
        # template) on their own theme-name change signal, not on the
        # underlying files changing in place — an already-running Nautilus
        # keeps showing the old wallpaper's folder colors until restarted.
        # `-q` is Nautilus' own documented quit flag (cleanly stops its
        # backgrounded D-Bus service); harmless no-op if it isn't running.
        hooks.colors_changed = [ "nautilus -q" ];

        # Bar defaults to background_opacity = 1.0 (fully opaque) — found
        # via live testing that this silently defeats niri's blur window/
        # layer-rules (rules.kdl): a fully-opaque surface has nothing
        # transparent for blur to show through (confirmed in niri's own
        # Window-Effects docs). "default" matches BarConfig's own default
        # name (confirmed live via `niri msg layers`: the real namespace is
        # "noctalia-bar-default"), so this overrides that one bar's
        # opacity rather than defining a second one.
        bar.default = {
          background_opacity = opacity;

          # The bar is the one Noctalia surface that takes a real pixel
          # radius, so it's where style.radius can be matched exactly against
          # niri's window corners rather than approximated. Was Noctalia's
          # own default of 12 against niri's 20 — close enough to look
          # accidental rather than deliberate, which is the whole complaint
          # this change answers.
          inherit (style) radius;
        };

        theme = {
          mode = "dark";
          source = "wallpaper";
          wallpaper_scheme = "m3-content";

          templates = {
            # These ids are documented nowhere upstream — they were
            # confirmed by reading assets/templates/builtin.toml directly
            # in the noctalia flake input's source (the [catalog.*]
            # entries are the real builtin_ids). "ghostty" keeps
            # ~/.config/ghostty/themes/noctalia in sync with the
            # wallpaper (see home/ghostty.nix); "gtk3"/"gtk4"/"qt" close
            # the GTK/Qt theming gap open since Phase 3. Deliberately NOT
            # "starship" here — its official template live-edits
            # ~/.config/starship.toml directly (sed-inserting a palette
            # line + marked block); replaced by our own custom user
            # template below instead, which avoids that conflict by
            # design (see templates.user.starship).
            #
            # "niri" (added after a fresh-bootstrap investigation):
            # confirmed via builtin.toml's own [templates.niri] that this
            # is what actually writes ~/.config/niri/noctalia.kdl (focus
            # ring/border/shadow colors) — it was never on this list
            # despite that file already being consumed by
            # home/niri.nix's config.kdl (`include "./noctalia.kdl"`,
            # Phase 3). It had apparently been generated anyway on
            # already-provisioned hosts (this repo's own history notes
            # the file existing and updating correctly), which masked the
            # gap — but a genuinely fresh nixos-anywhere install of the
            # VM showed niri failing to start at all on its first login
            # (`failed to read included config from ".../noctalia.kdl":
            # No such file or directory`) before Noctalia's template pass
            # had ever run once to create it. Its own apply.sh writes the
            # output file and is idempotent/self-healing about the
            # config.kdl include line (matches "noctalia.kdl" with any
            # leading path, so it recognizes home/niri.nix's existing
            # `include "./noctalia.kdl"` and never duplicates it) — no
            # conflict with anything Nix manages.
            builtin_ids = [
              "ghostty"
              "gtk3"
              "gtk4"
              "niri"
              "qt"
            ];

            # Deliberately NOT "neovim" here — its official community
            # template turned out to be a *different* file from the
            # operator's own neovim_dotfiles copy (Noctalia fetches and
            # caches its own matugen-template.lua from
            # github:noctalia-dev/community-templates, entirely separate
            # from ~/.config/nvim's own git history), both writing the
            # same ~/.config/nvim/lua/matugen.lua — a real risk of one
            # silently overwriting the other depending on ordering.
            # Replaced by our own custom user template below instead
            # (see templates.user.neovim), giving us the one actual
            # source of truth for this file, matching the
            # starship/lazygit precedent.
            #
            # Deliberately NOT "lazygit" — its community template
            # rewrites ~/.config/lazygit/config.yml directly via `mv`,
            # conflicting with the Nix-managed home/lazygit.nix from
            # Phase 4 the same way starship's builtin template would;
            # replaced by our own custom user template below instead.
            #
            # "yazi" only — not a separate "yazi-syntax" entry too.
            # Confirmed by reading template_apply_service.cpp directly:
            # communityIds entries key a *cached catalog directory*
            # (community-templates' own yazi/template.toml), fetched and
            # then fully processed as one file — and that one file
            # happens to define both [templates.yazi] (flavor colors) and
            # [templates.yazi-syntax] (tmTheme), both applied together
            # once "yazi" is cached. "yazi-syntax" isn't its own
            # fetchable catalog entry; listing it separately would just
            # produce a "not cached yet" warning, the same one seen
            # earlier for "lazygit" before that was dropped in favor of
            # the custom template. Both outputs land in a clean, separate
            # directory (~/.config/yazi/flavors/noctalia.yazi/) — no
            # conflict, since home/yazi.nix doesn't manage any yazi config
            # with Nix at all.
            # "papirus-icons" (Theming phase): recolors Papirus' folder
            # icons to the nearest papirus-folders preset for the current
            # wallpaper accent (HSV-nearest match against
            # colors.source_color, confirmed by reading the template's own
            # apply.sh). Its fallback `cp -r /usr/share/icons/Papirus` path
            # doesn't exist on NixOS — home/gtk.nix seeds a writable
            # $HOME/.local/share/icons/Papirus copy itself so that check
            # always finds the directory already present and this fallback
            # never triggers.
            # "discord" (Phase 6): writes vesktop's noctalia/noctalia-material
            # theme CSS into ~/.config/vesktop/themes/ — a separate directory
            # home/vesktop.nix never touches (see that file's own comment),
            # so no conflict.
            # "vscode" (Phase 6): writes a color-theme JSON into the
            # noctalia.noctaliatheme VS Code extension's own bundled
            # directory (~/.vscode/extensions/...), which only exists once
            # that extension is installed via Settings Sync (home/vscode.nix
            # deliberately doesn't manage VS Code config at all — see that
            # file). Separate output file either way, no conflict.
            # "zen-browser" (Phase 6): writes userChrome/userContent CSS to a
            # cache dir, then its own apply.sh appends an @import line into
            # the actual Firefox-style profile's userChrome.css/userContent.css
            # and flips two about:config prefs — mutable profile state Nix
            # never manages (home/zen-browser.nix), so no conflict either.
            # "feishin" (Phase 6): writes a separate
            # $XDG_CONFIG_HOME/feishin/custom.css — home/feishin.nix doesn't
            # manage any Feishin config at all (its real config carries
            # actual music-server credentials, deliberately never read into
            # this repo), so no conflict.
            # "obsidian" (Phase 6): discovers every local vault
            # (any ".obsidian" dir under $HOME) and writes/enables its own
            # CSS snippet inside each one's snippets/ folder —
            # home/obsidian.nix doesn't manage any vault content, so no
            # conflict.
            community_ids = [
              "yazi"
              "papirus-icons"
              "discord"
              "vscode"
              "zen-browser"
              "feishin"
              "obsidian"
            ];

            # Custom templates, written and checked into this repo
            # (home/noctalia-templates/), for the two cases where the
            # official (builtin/community) template would conflict with
            # a file Home Manager already manages. Since we control
            # input_path/output_path/post_hook completely here — unlike
            # the official templates, which must stay compatible with an
            # arbitrary pre-existing user file via in-place sed/mv edits
            # — these render their *entire* output file fresh each time,
            # the same way ghostty/gtk/qt/niri's own templates already
            # behave, sidestepping the conflict entirely rather than
            # working around it.
            user = {
              # The shape half of the shared style vocabulary, for niri.
              # Unlike the three below, this one exists not because an
              # official template would conflict, but because no official
              # template covers window *geometry* at all — the builtin "niri"
              # template writes colors only. See niriStyleTemplate above for
              # why the input is generated by Nix rather than checked in as a
              # static .tmpl: the numbers have to come from the `style` block.
              #
              # No post_hook: niri watches its own config (and its includes)
              # and reloads on change, which is the same thing the builtin
              # "niri" color template relies on. Adding one would be a second,
              # redundant reload path.
              niri-style = {
                input_path = niriStyleTemplate;
                output_path = [ "$XDG_CONFIG_HOME/niri/noctalia-style.kdl" ];
              };

              starship = {
                input_path = ./noctalia-templates/starship.toml.tmpl;
                # No post_hook needed: Starship re-reads its config file
                # on every new prompt render, no daemon/signal to
                # restart. home/starship.nix deliberately has no
                # `settings` — this template is the sole owner of the
                # whole file.
                output_path = [ "$XDG_CONFIG_HOME/starship.toml" ];
              };

              lazygit = {
                input_path = ./noctalia-templates/lazygit-theme.yml.tmpl;
                # Deliberately a SEPARATE file from home/lazygit.nix's
                # Nix-managed config.yml (nerdFontsVersion,
                # notARepository) — merged at invocation time via
                # LG_CONFIG_FILE (see home/lazygit.nix's
                # home.sessionVariables), not by overwriting config.yml.
                # Keeps the already-completed Phase 4 home/lazygit.nix
                # completely untouched.
                output_path = [ "$XDG_CONFIG_HOME/lazygit/themes/noctalia.yml" ];
              };

              neovim = {
                input_path = ./noctalia-templates/neovim-matugen.lua.tmpl;
                # Same content as the (now superseded) get_palette() fix
                # pushed to github:TechieOllie/neovim_dotfiles's own
                # lua/matugen-template.lua, just relocated here to be the
                # one actual source of truth (see community_ids' comment
                # above for why the official community template was
                # dropped instead of used). ~/.config/nvim's own
                # lua/plugins/ui.lua reads this file's get_palette() to
                # drive its own highlight overrides (Telescope, Diffview,
                # LSP diagnostics, and the transparent-background groups
                # added alongside this).
                output_path = [ "$XDG_CONFIG_HOME/nvim/lua/matugen.lua" ];
                # Signals already-running nvim processes to hot-reload,
                # matching the SIGUSR1 handler baked into the template
                # itself (and what Noctalia's own official template's
                # apply.sh did) — `|| true` since pkill exits non-zero
                # when no nvim process is running.
                post_hook = "pkill -SIGUSR1 nvim || true";
              };
            };
          };
        };

        # Deliberately no default.path/enabled here — confirmed live that
        # Noctalia only ever reads the *active* wallpaper from its own
        # ~/.local/state/noctalia/settings.toml (set via `noctalia msg
        # wallpaper-set` or its own UI), never from config.toml. Setting a
        # default here would either do nothing, or (via an autostart
        # workaround) permanently re-pin the wallpaper on every login,
        # overwriting any choice made through Noctalia's own UI. Instead,
        # just point the picker at this repo's wallpapers/ directory.
        #
        # Deliberately a plain string, NOT a Nix path (e.g. ../wallpapers) —
        # a path literal gets copied into the Nix store as its own
        # derivation output the moment it's stringified, doubling storage
        # (repo checkout + store copy) and requiring a full rebuild+switch
        # just to pick up a newly added wallpaper file. Pointing at the
        # repo's own on-disk clone instead means: one copy of the files,
        # and dropping a new wallpaper in just works with no rebuild.
        # Requires this repo to be cloned to ~/.dotfiles on every host that
        # uses this module — see docs/live-dotfiles.md.
        wallpaper.directory = "/home/${vars.user.name}/.dotfiles/wallpapers";
      };
    };

    # Seeds noctalia-style.kdl so niri can always resolve config.kdl's
    # `include "./noctalia-style.kdl"`, even before Noctalia's template engine
    # has ever run.
    #
    # This is not belt-and-braces — it's the exact failure this repo already
    # hit once. A genuinely fresh nixos-anywhere install of the VM had niri
    # refuse to start on its first login with `failed to read included config
    # from ".../noctalia.kdl": No such file or directory`, because greetd
    # launches niri well before Noctalia's first re-theme pass exists to
    # create the included file. A missing include is fatal to niri, not a
    # warning, and adding a second included file without this would reproduce
    # that bug exactly — on a host whose only way back in is a TTY.
    #
    # A plain copy rather than an xdg.configFile: Noctalia's template engine
    # must be able to *write* this path, and a read-only Nix store symlink is
    # precisely what broke noctalia.kdl before (see home/niri.nix's own note
    # on that). Same shape as home/gtk.nix's seedPapirusIcons — seed a real,
    # writable file that a runtime tool then owns.
    #
    # Re-seeded unconditionally on every activation, not `cp -n`: the content
    # is generated from the `style` block above and contains no palette data,
    # so Noctalia's own render of the same template is byte-identical. There
    # is nothing to preserve and no fight to lose — but changing style.radius
    # does need to reach the file even when it already exists, which a
    # create-if-missing seed would silently skip.
    home.activation.seedNiriStyle = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
      run mkdir -p "$HOME/.config/niri"
      run cp -f "${niriStyleTemplate}" "$HOME/.config/niri/noctalia-style.kdl"
      run chmod u+w "$HOME/.config/niri/noctalia-style.kdl"
    '';
  };
}
